### ISSUE TITLE
hello, your tools is very usful ,thank you very much! and i have a bug to report

### ISSUE THREAD

**Issue by goxofy** [rahuliyer/flickr_uploader#1]
if i already have a set named "AA", and then i use this tool to upload photos to the set, but it will create a new set named"AA"....

my set name is in Chinese

**Comment by rahuliyer** [comment]
Hey goxofy,
Yes, I'm aware of this and is something I intend to fix. I hope to have a fix for this within a week.

**Comment by goxofy** [comment]
thx!!

**Comment by rahuliyer** [comment]
Fixed. Let me know if it works.

**Comment by goxofy** [comment]
i guess something wrong ... my sets is in Chinese, and the program console log:

```
flickr_uploader.py:108: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if set.lower() == sets[id].lower():
```

and then it will also create a new set.

**Comment by rahuliyer** [comment]
ah... it's a unicode issue. Worked in English :( I'll fix soon. Working on a different feature at the moment.

**Comment by goxofy** [comment]
thank you very much !

**Comment by rahuliyer** [comment]
Can you try now? Should work.

**Comment by goxofy** [comment]
i'm sorry to tell u.. it also put log

```
flickr_uploader.py:115: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if set == sets[id]:
Successfully created set 杂图
Successfully added ../1/1.jpg to 杂图
```

i dont know why...

**Comment by rahuliyer** [comment]
Could you give me the command line you're using? That will help me a lot to fix this issue.

**Comment by rahuliyer** [comment]
Leaving out the app id and secret of course :)
